### ISSUE TITLE
More secure accountant fee implementation 

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1313] opened 2019-09-30 08:46 UTC
In order to eliminate possible cheating my Accountant we must include fee into promise so that Accountant would be obliged to payout exact agreed sum and not to increase a fee in a process.

**Comment by chompomonim** [comment] 2019-10-01 21:38
duplicate of https://github.com/mysteriumnetwork/accountant/issues/17

**Closed by chompomonim** 2019-10-01 21:38 UTC
Labels: Payments, component:payments-smart-contracts
