### ISSUE TITLE
ChainID resets to 0

### ISSUE THREAD

**Issue by tomasmik** [mysteriumnetwork/node#4806] opened 2022-02-22 15:08 UTC
{"level":"error","error":"unknown chain","clientIP":"104.193.104.2","method":"POST","path":"/api/v2/reveal_r","requestID":"48dd96dd-ff37-49fb-9bd2-a50c4356ec06","chain_id":0,"time":"2022-02-22T14:49:39.381052082Z","message":"could not get provider channel"}

**Comment by Guillembonet** [comment] 2022-03-07 12:38
duplicate of #4820

**Closed by Guillembonet** 2022-03-07 12:38 UTC
Labels: bug
