### ISSUE TITLE
All traffic is served for free

### ISSUE THREAD

**Issue by tadaskay** [mysteriumnetwork/node#2388] opened 2020-06-16 12:10 UTC
**Describe the bug**
In the last week or so, sessions of any duration/data transferred all cost 0 MYSTT

**To Reproduce**
1. Open desktop app
2. Connect to any provider
3. Download smth
4. Observe "Paid" amount

**Expected behavior**
The paid amount should be calculated based on data transferred/duration.

**Screenshots**
<img width="653" alt="Screenshot 2020-06-16 at 15 09 30" src="https://user-images.githubusercontent.com/4745368/84772315-72ff6a80-afe3-11ea-839b-beb6f1988c61.png">

**Environment (please complete the following information):**
 - Node version: master
 - OS: any
 - Desktop app version (if applicable): master

**Comment by vkuznecovas** [comment] 2020-06-18 10:59
Caused by incompatible exchange message format and #2393

**Comment by chompomonim** [comment] 2020-07-07 10:48
This is fixed in 0.35 node version

**Closed by chompomonim** 2020-07-07 10:48 UTC
Labels: blocked, bug, component:node, payments
