### ISSUE TITLE
Updates to release process

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1630] opened 2020-02-04 12:06 UTC
## Problem statement

 - Improve on timely releases with a bit more confidence in quality.
 - Ability to backport critical fixes for stable already released versions. (Currently we aim to support releases for last 30 days)
 - Make release cycle more mainnet-like
 - Freeze and start testing all main features and new features for all products and main platforms.
 - Automate RPI releases with more confidence

## Proposed modifications

 - Create a new branch for each soon to be released version. For example we are going to release 0.21.0, we should create such branch, create a pre-release and start testing it. 
 - When team finishes testing, release is made from that "0.21.0" branch.
 - All future critical bugs affecting network operation should be backported to "0.21.0" branch for 30 days since its initial release.

This will require us identify and set up a manual testing process. Will create a separate ticket for this describing for of a testing process.

**Comment by chompomonim** [comment] 2020-02-04 15:42
Duplicate of #1612

**Closed by chompomonim** 2020-02-04 15:42 UTC
Labels: component:node, proposal
