### ISSUE TITLE
[android] sendto: operation not permitted, could not fetch fees

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#4305] opened 2021-11-20 12:14 UTC
**Describe the bug**
Can't get node running properly on Android.
I can see multiple errors. Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7574507/mysterium-node.log)

**Environment (please complete the following information):**
 - Node version: 0.68.1
 - OS: Android

**Comment by tomasmik** [comment] 2021-11-20 17:27
Duplicate of https://github.com/mysteriumnetwork/node/issues/4257

**Closed by tomasmik** 2021-11-20 17:27 UTC
Labels: bug
