### ISSUE TITLE
Identity backup/restore from CLI and WebUI

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#1650] opened 2020-02-06 02:57 UTC
There are cases when an app upgrade will mean a change of identity. This was not an issue before but now with embedded payments, earned and spend tokens are controlled by identities private key and we should have an easy way to backup and restore it.

**Comment by soffokl** [comment] 2020-02-06 03:11
It's a duplicate of https://github.com/mysteriumnetwork/node/issues/1637

**Closed by soffokl** 2020-02-06 03:11 UTC
Labels: component:cli, component:web-ui
