### ISSUE TITLE
0 MYSTT / $0 for almost 1TB data

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2082] opened 2020-04-17 06:09 UTC
Identity id: 0xe18b4d82cc538d6b2d004456ee5a0dc985b441c0, 0.22.5, RPi
This node has transferred 988GB of data and generated 506 sessions while this month's earnings is 0 MYSTT / $0. A lot of sessions with 58m, 6s(1.26GB), 1s and 0B duration.

**Comment by zolia** [comment] 2020-04-17 06:23
I don't see any log submitted. In particular i am interested on those 6s(1.26GB) sessions.

**Comment by vkuznecovas** [comment] 2020-04-17 07:41
My theory:

We have confirmed a bug with openvpn sessions not being destroyed on the provider side if payments fail.(#1838)

This causes the following behaviour:

Consumer connects, provider sends invoice, gets exchange message. The exchange message is then passed on to the accountant, who returns an overcharge error. The provider sees the error, cancels the session. The session time is set to a few seconds and submitted to metrics.

However, openvpn key exchange has already occured, and the session stays hanging on for nearly an hour until reauth occurs. During this hour, traffic is transfered and reported by the consumer, but not paid for.

**Comment by zolia** [comment] 2020-04-17 09:14
But we see these 1.6T sessions from provider submitted metrics only. We don't see those reported from consumer since no data about it on discovery. And this cannot be if actual transfer took place?

**Comment by zolia** [comment] 2020-04-17 09:21
found them, they all were wireguard sessions.. meaning they were not superproxy :) 
https://testnet.mysterium.network/node/0xe18b4d82cc538d6b2d004456ee5a0dc985b441c0/wireguard

**Comment by zolia** [comment] 2020-04-17 10:00
Its an agent connects with proper balance, bus payment do not go through the provider. Accountant sees nothing. Need to investigate provider logs.

**Comment by etherunit** [comment] 2020-04-19 10:22
Still waiting for the node logs from 0xe18b4d82cc538d6b2d004456ee5a0dc985b441c0
In the meantime, have received another logs from 0xdb5eefabe86098ad541429177b6bcbc1fd83514b which made 1.91 TB and earned 4.31$ only. This specific case also includes a very short sessions (8s) with 1.03GB data transfers so it might be related. 

User report https://github.com/mysteriumnetwork/node-user-reports/issues/495
https://github.com/mysteriumnetwork/node-user-reports/issues/494

Download report: https://my.mysterium.network/admin/download/495

**Comment by vkuznecovas** [comment] 2020-04-20 08:37
This is already fixed in the new version. Once released, auto updates will fix it.

**Closed by vkuznecovas** 2020-04-20 08:37 UTC
Labels: bug

**Comment by zolia** [comment] 2020-04-20 08:38
@etherunit recommend user to update to 0.31.0-rc2 for now or wait for auto-update when released.
