### ISSUE TITLE
No recorded earnings since mid Feb

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4815] opened 2022-02-24 09:44 UTC
**Describe the bug**
Node "0xad245a0b1b8b09d9cf0a7c25cea70fa72ebf71d2" has no recorded earnings since mid Feb

(https://mystnodes.com/support/logs/2022-02-24-66f9ed33-2359-4c8c-8f18-96258c16c7ce-mysterium-node.zip2767353600)

**Screenshots**
<img width="794" alt="Screenshot 2022-02-24 at 09 44 32" src="https://user-images.githubusercontent.com/84313603/155499524-a7dbeec0-521b-40e6-865f-72059aaf7679.png">

**Comment by msvanvertloo** [comment] 2022-02-25 03:07
Looks like the same behavior I'm seeing.  Lots of errors like this started happening on 21-Feb, at the same time I stopped earning from sessions:

WRN session/pingpong/invoice_tracker.go:534  > hermes error, will retry error="hermes request promise error: could not reveal R: could not reveal R for hermes: internal error"

**Comment by etherunit** [comment] 2022-02-28 07:11
@isaackielma Could you please request node logs from this provider? It could be useful to see it.

**Comment by isaackielma** [comment] 2022-02-28 16:52
@etherunit The link should get you to the logs I believe: (https://mystnodes.com/support/logs/2022-02-24-66f9ed33-2359-4c8c-8f18-96258c16c7ce-mysterium-node.zip2767353600)

Let me know otherwise.

**Comment by msvanvertloo** [comment] 2022-03-02 15:21
I don't know that I would call this "minor".  I've probably missed out on ~150 MYST since this started happening.  I'm about to shut down my node until this is resolved.

**Comment by Guillembonet** [comment] 2022-03-04 09:10
> I don't know that I would call this "minor". I've probably missed out on ~150 MYST since this started happening. I'm about to shut down my node until this is resolved.

@msvanvertloo can you provide your node id? also logs would be useful. Make sure to update your node to the latest version, we solved many withdrawal issues in recent updates. Also, your funds are not lost, even if they seem to be disappeared they are not and you can still claim them all.

**Comment by Guillembonet** [comment] 2022-03-04 09:15
> @etherunit The link should get you to the logs I believe: (https://mystnodes.com/support/logs/2022-02-24-66f9ed33-2359-4c8c-8f18-96258c16c7ce-mysterium-node.zip2767353600)
> 
> Let me know otherwise.

That is weird, in those logs it's totally normal that he has no earnings, there is no sessions and the node has only been on for 3 minutes. It's possible that he migrated his node and kept the logs folder of another one, not sure what is going on. @isaackielma make sure his node is on and if so make him send logs again pls

**Comment by msvanvertloo** [comment] 2022-03-04 15:31
@Guillembonet Note: this has nothing to do with withdrawals.  This is the fact that my node (0x308f1be6ac3ea1b7cbc8ae8d3c3c8503b849b9fd) served up 100GB of data over the last two weeks and my unsettled balance never moved.  All sessions were recorded as zero.  So, while perhaps I didn't lose money, I also didn't earn money where I should have.

**Comment by Guillembonet** [comment] 2022-03-07 09:08
> @Guillembonet Note: this has nothing to do with withdrawals. This is the fact that my node (0x308f1be6ac3ea1b7cbc8ae8d3c3c8503b849b9fd) served up 100GB of data over the last two weeks and my unsettled balance never moved. All sessions were recorded as zero. So, while perhaps I didn't lose money, I also didn't earn money where I should have.
> 
> I took my node offline, so I don't have logs at this time. No use selling bandwidth for zero.
> 
> The error preventing invoicing is, I believe, what I posted in an earlier comment.

Yes that seems to be the issue, but logs are needed to see what is causing it

**Comment by Guillembonet** [comment] 2022-03-07 12:44
duplicate of #4820 @msvanvertloo you can follow the progress there :)

**Closed by Guillembonet** 2022-03-07 12:44 UTC
Labels: bug, minor
