### ISSUE TITLE
libgojni.so Library Causing Crashes on Android Devices

### ISSUE THREAD

**Issue by furkanarius** [mysteriumnetwork/node#3701] opened 2021-07-28 10:54 UTC
**Describe the bug**
There's a bug that's causing 10% crash rate on Android, which puts us way above the acceptable threshold. However, we haven't been able to determine the cause of the bug as there's no stack trace and no logs.

All OS and device types are crashing, which means it's not specific to a certain device/OS type.

The bug can be seen here:
https://play.google.com/console/u/2/developers/5477358562317575210/app/4975255075173278773/vitals/crashes/15c662a2/details?versionCode=107109

**Comment by Snawoot** [comment] 2021-08-10 23:05
@furkanarius I can't access provided link. Can you please attach logs, stacktraces, whatever is available to you?

**Comment by furkanarius** [comment] 2021-08-11 06:44
If I'm not mistaken @tadaskay had some logs from an Android crash, he can send it to you once he's back

**Comment by Snawoot** [comment] 2021-08-11 06:52
@furkanarius Thank you!

**Comment by Snawoot** [comment] 2021-08-12 11:22
Seems like duplicate of #3687

**Closed by Snawoot** 2021-08-12 11:22 UTC
Labels: bug, component:mobile
