### ISSUE TITLE
Consumer connect / disconnect race conditions

### ISSUE THREAD

**Issue by anjmao** [mysteriumnetwork/node#1427] opened 2019-11-26 12:35 UTC
While working on mobile I was able to get into state when consumer connects multiple times and even after disconnect I was getting statistic events from two different connections.

In order to reproduce run mobile android app and click Connect -> Cancel button multiple times non stop.

**Comment by tadaskay** [comment] 2020-03-04 20:02
Can confirm this on desktop, too: since the new POC allows to connect with one-click, it occurs rather often.

**Comment by soffokl** [comment] 2020-07-03 03:31
I failed to reproduce it on the latest version. Since the issue is very old most likely it was fixed indirectly. 
If you will have a reproducible case, please reopen the issue.

**Closed by soffokl** 2020-07-03 03:31 UTC
Labels: bug, component:node
