### ISSUE TITLE
[android, bug] can't start node "could not get hermes url: daily request count exceeded, request rate limited"

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3120] opened 2021-02-16 10:02 UTC
Node: 0.42.1

mysterium.Mysterium.newNode (Mysterium.java)
network.portals.service.core.MysteriumAndroidCoreService.startMobileNode (MysteriumAndroidCoreService.kt:42)

Error:
could not bootstrap dependencies: could not get hermes url: daily request count exceeded, request rate limited

Looks like something on the server-side?

**Comment by vkuznecovas** [comment] 2021-02-16 10:52
This is duplicate of #3117. We're working on multiple fronts to solve this :)

**Closed by vkuznecovas** 2021-02-16 10:52 UTC
Labels: bug

**Comment by cvl** [comment] 2021-02-16 11:00
Good luck :)
