### ISSUE TITLE
Sessions are not being paid properly

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#4827] opened 2022-03-01 13:57 UTC
**Describe the bug**

Node ID: 0x87217d7430568d8ce115729cdd00707c76737b0e

No transactions payment.
6 pages are without pay for use.

Logs:

https://mystnodes.com/support/logs/2022-03-01-135805e1-de5e-44c4-96e7-a4dfa397d094-mysterium-node.zip979445684

Screenshots:

<img width="426" alt="Screenshot 2022-03-01 at 10 54 33" src="https://user-images.githubusercontent.com/84313603/156182084-3d5746ec-bfbd-49b7-9fbf-0d383a434770.png">
<img width="381" alt="Screenshot 2022-03-01 at 10 54 43" src="https://user-images.githubusercontent.com/84313603/156182102-0c3a81a8-315d-4233-be71-e66651c06a3f.png">
<img width="374" alt="Screenshot 2022-03-01 at 10 54 52" src="https://user-images.githubusercontent.com/84313603/156182107-b5fe7a1a-20e5-4600-8137-10d229d0f753.png">
<img width="376" alt="Screenshot 2022-03-01 at 10 55 05" src="https://user-images.githubusercontent.com/84313603/156182111-c984658a-23c0-487f-babb-3025b9159148.png">
<img width="383" alt="Screenshot 2022-03-01 at 10 55 28" src="https://user-images.githubusercontent.com/84313603/156182113-6a3f53c1-5ec2-4056-999d-15d8e6a545d5.png">
<img width="382" alt="Screenshot 2022-03-01 at 10 55 38" src="https://user-images.githubusercontent.com/84313603/156182118-c64d549d-0e50-4ecb-91f5-679aa22f6dab.png">

**Comment by etherunit** [comment] 2022-03-06 07:28
@isaackielma What is node version? Suggest him to update to the latest node version. This way we can verify if issue remains unfixed.

**Comment by etherunit** [comment] 2022-03-06 07:29
```
2022-03-01T03:22:43.404 INF session/pingpong/hermes_promise_handler.go:417 > Recovering R...
2022-03-01T03:22:43.404 INF session/pingpong/hermes_promise_handler.go:434 > R recovered, will reveal...
2022-03-01T03:22:43.573 WRN session/pingpong/invoice_tracker.go:534  > hermes error, will retry error="hermes request promise error: could not reveal R: could not reveal R for hermes: internal error"
```

**Comment by etherunit** [comment] 2022-03-06 07:33
@tomasmik Could it be a reason for not allocated MYSTs?

**Comment by daboogie123** [comment] 2022-03-08 12:23
Updated to latest

**Comment by Guillembonet** [comment] 2022-03-08 12:27
> 0x87217d7430568d8ce115729cdd00707c76737b0e

This is a duplicate of #4820 
I manually fixed it on our end, now it should be working fine. Let me know if it's not!

**Closed by Guillembonet** 2022-03-08 12:27 UTC
Labels: bug
