### ISSUE TITLE
kill switch for mobile and desktop apps

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#1675] opened 2020-02-10 14:26 UTC
Related: https://github.com/mysteriumnetwork/node/issues/375
https://github.com/mysteriumnetwork/node/issues/373

CC: @chompomonim

**Comment by cvl** [comment] 2020-02-20 11:58
Is this under consideration?

**Comment by chompomonim** [comment] 2020-02-22 14:23
It is, but not a top priority for now.

**Comment by cvl** [comment] 2020-02-24 08:18
I can see that there's some work on this, isn't it? https://github.com/mysteriumnetwork/node/issues/1752

**Comment by cvl** [comment] 2020-03-17 14:38
@chompomonim any thoughts on this?

**Comment by chompomonim** [comment] 2020-03-18 00:26
Kill switch is an important feature. However, our main focus for the next a few months will be not adding new features, but making app stability and going mainnet. I do expect that works on kill switch can be done not earlier than Q3 this year.

**Comment by zolia** [comment] 2020-06-03 07:26
Kill switch should be straightforward to implement on darwin using pfctl and not so on Windows.
Main issue here is that we need to be able to restore proper desktop state right after we stop the connection. This functionality should migrate to supervisor.

**Comment by cvl** [comment] 2020-08-04 14:09
Any plans for this?

**Comment by chompomonim** [comment] 2020-08-07 23:24
Quite high priority but after mainnet.

**Comment by cvl** [comment] 2020-08-31 15:48
Possible to do this sooner, as mainnet will take months?

**Comment by chompomonim** [comment] 2020-09-03 07:17
After betanet release we're going to work on new roadmap and priorities for features we'd like to add until New Year. I think kill switch will be in that list.

**Comment by cvl** [comment] 2020-11-25 13:45
Any progress on this?

**Comment by chompomonim** [comment] 2020-11-26 12:36
After betanet release...

**Comment by chompomonim** [comment] 2021-03-07 21:40
This is duplicate of other tasks, please look at #375 and #373

**Closed by chompomonim** 2021-03-07 21:40 UTC
Labels: component:mobile, feature request

**Comment by cvl** [comment] 2021-03-08 08:10
Then we need another issue for Android.

**Comment by chompomonim** [comment] 2021-03-08 13:59
You mean this one? #3168

**Comment by cvl** [comment] 2021-03-08 14:17
Yes, this one :D
