### ISSUE TITLE
Payment engine error

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#1582] opened 2020-01-29 10:35 UTC
Provider is running on 0.19.1, however he is not receiving any MYSTT for the transactions he is doing. There are plenty of sessions >1min (min duration needed) Logs below:

`{"error":"Consumer's promise value is not big enought. Should be at least 5349983143MYST"} 2020-01-25T23:49:56.007 WRN source/session/pingpong/invoice_tracker.go:239 > Could not call accountant error="could not request promise from accountant: server response invalid: 400 Bad Request (https://testnet-accountant.mysterium.network/api/v1/request_promise)" 2020-01-25T23:49:56.008 ERR source/session/manager.go:185 > Payment engine error error="failed to get exchange message: could not call accountant: could not request promise from accountant: server response invalid: 400 Bad Request (https://testnet-accountant.mysterium.network/api/v1/request_promise)" 2020-01-25T23:49:56.008 DBG source/session/pingpong/invoice_tracker.go:505 > Stopping...`

**Comment by vkuznecovas** [comment] 2020-01-29 13:56
This is caused by running multiple instances of node with the same identity.

The consumer that's connecting to your node is running multiple consumers with the same identity, hence the state between those consumers gets desynchronized, meaning that the promises they issue are not valid and get rejected. Due to the leeway we've set on the initial payment alpha these messages get displayed for quite a bit until eventually the provider node causes the session to be closed. 

This behaviour is intended and everything is working as expected. The consumer is not supposed to share his identity between multiple nodes. Once testing is over, this sort of behaviour will cause the consumer to get sessions cancelled almost instantly, meaning no service will be provided. 

I've contacted the relevant consumer and they've promised to change the way they are using node on their side.

Since the behaviour is by design, I'm closing this.

**Closed by vkuznecovas** 2020-01-29 13:56 UTC
Labels: bug, system:osx
