### ISSUE TITLE
Mysterium node UI earnings report data is incorrect for the 30-day period

### ISSUE THREAD

**Issue by m4rduc** [mysteriumnetwork/node#5655] opened 2022-11-28 21:42 UTC
**Describe the bug**
Mysterium node UI earnings report data is incorrect for the 30-day period

**To Reproduce**
Go to node UI
compare 24hr, 7-day, and 30-day earnings reports.
When the 30-day report is selected the total earnings, sessions, session time, and transferred data along the bottom of the report will not display the correct data for a 30-day period.
It will duplicate the last select period data either 24 hours or 30 days.

**Expected behavior**
it should show the unique data for a 30 day period

**Screenshots**
![7 Days](https://user-images.githubusercontent.com/89709253/204385934-818651f4-51cb-46e9-9219-83a80d38edc2.PNG)
![30 Days](https://user-images.githubusercontent.com/89709253/204385966-9aaed8ba-ef8b-4384-aae9-d8f71190a77f.PNG)

**Environment (please complete the following information):**
 - Node version: [1.19.5] Node UI version [2.3.2]
 - OS: [Ubuntu 20.04.5 LTS]
 - Desktop app version (if applicable): N/A
 - Docker (if applicable): N/A
 - Your identity (if applicable): [0x1f08cdcace7c37257e71221a179295adddf6913e]
 - Payment (top-op) reference (if applicable): N/A

**Additional context**

**Comment by etherunit** [comment] 2022-12-01 09:50
It's duplicate of https://github.com/mysteriumnetwork/node/issues/5576
Please note that it's in progress (team is working on it).

**Comment by m4rduc** [comment] 2022-12-06 17:23
good to hear it's already in hand. Should I close this report as its a duplicate?

**Comment by etherunit** [comment] 2022-12-13 07:10
Yep, we can close it and track the following one https://github.com/mysteriumnetwork/node/issues/5576

**Closed by etherunit** 2022-12-13 07:10 UTC
Labels: bug
