### ISSUE TITLE
Active connections show wrong number (does not match dashboard)

### ISSUE THREAD

**Issue by mjankauskas** [mysteriumnetwork/node#943] opened 2019-05-02 13:06 UTC
After starting node and multiple connections App shows more active connections then dashboard in testnet

**Comment by vkuznecovas** [comment] 2019-05-07 09:25
I've been trying to reproduce this for a couple of hours. No matter what amount of connect/disconnect cycles I do both the dashboard and the /service-sessions tequila endpoint return a correct amount of sessions. There's a slight delay on the dashboard though and that's by design.

I've spoken to @ignasbernotas and the application only fetches the /service-sessions and shows the .length of the result. Therefore, the issue is related to node, not desktop.

The only possible way this is happening is when a consumer fails to send a session destroy. This leaves a ghost session on the provider. The dashboard does not register such session therefore you get the discrepancy. However, this ghost session eventually times out(it's hardcoded @ 2 hours now). The long timeout is required due to the way wireguard works(we want to keep the session a live for a while on the provider for it). 

This is also exaggerated with the old versions of consumer. Old consumers had a bug which caused them to fail to announce their session destroy, leaving ghost sessions. #815 fixed the issue, so this should be a non factor in an up to date version.

I'm closing this @mjankauskas. If there's something I've missed - or you think this is critical to be solved - reopen it.

**Closed by vkuznecovas** 2019-05-07 09:25 UTC
Labels: bug, component:desktop, epic:desktop-patchworks
