### ISSUE TITLE
sessions with 58 min duration are not counted

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2076] opened 2020-04-16 09:00 UTC
This node 0xa0e450b6213f465057dd387ef07b051e099a8345 has plenty of sessions = 58m which are not calculated into tokens.
monthly earnings $0.53 and it should be at least $5 for 73gb.
user report: **https://github.com/mysteriumnetwork/node-user-reports/issues/469**

Direct link to node report download: https://my.mysterium.network/admin/issues/download/469

<img width="1288" alt="Screenshot 2020-04-16 at 12 00 31" src="https://user-images.githubusercontent.com/60128746/79436721-e7b12b00-7fd9-11ea-9bbf-580cde0c78c4.png">

**Comment by vkuznecovas** [comment] 2020-04-20 08:46
Caused by this: https://github.com/mysteriumnetwork/node/issues/1838

**Comment by chompomonim** [comment] 2020-04-28 11:12
It should be fixed. Could you recheck is issue is still there?

**Comment by vkuznecovas** [comment] 2020-05-05 08:29
#1838 closes this as well

**Closed by vkuznecovas** 2020-05-05 08:29 UTC
Labels: bug
