### ISSUE TITLE
NodeUi: All services offline

### ISSUE THREAD

**Issue by Peter-SovietSquirrel** [mysteriumnetwork/node#5311] opened 2022-07-18 19:00 UTC
Without any user interaction in NodeUi Node status will say No services available. The service will still be running transferring data and is visible in discovery.
If this is left the the service will stop and it will not be in discovery and NodeUI will only show spinning circle is anything. At this point the actual Linux system will become unresponsive as it may take minutes to log in via SSH. 
If nothing is still not done the sometime after a period of time the system will return to normal but this may take hours.

The screenshots were taken when the system was unresponsive  

 - Node version: 0.1.9.5 
 - OS: Ubuntu 18.04.6 LTS

 This issue seem to happen when there has been a large amount of data transferred over a long continues length of time. 

[daba_node.zip](https://github.com/mysteriumnetwork/node/files/9134574/daba_node.zip)
![mystnodes1](https://user-images.githubusercontent.com/60095913/179583842-f25f3e13-47e2-42e9-ba5d-1e82e28d03e5.png)
![mystnodes2](https://user-images.githubusercontent.com/60095913/179583848-63d02b27-a00a-4dff-9e22-8fe1aa25f94a.png)

**Comment by Peter-SovietSquirrel** [comment] 2022-07-19 22:11
[node.logs7.txt.zip](https://github.com/mysteriumnetwork/node/files/9144998/node.logs7.txt.zip)

Another shutdown. at around 16:30 the service stopped being able to transfer data and it went offline including the Linux system until around 22:51 that everything returned to normal.

**Comment by etherunit** [comment] 2022-07-21 04:54
Thanks for reporting @Peter-SovietSquirrel 
We will investigate it further

**Comment by Peter-SovietSquirrel** [comment] 2022-07-23 18:28
[heap.out.zip](https://github.com/mysteriumnetwork/node/files/9174412/heap.out.zip)

Outputs of the myst process using 250 & 500MB

**Comment by Peter-SovietSquirrel** [comment] 2022-07-23 18:45
[goroutine.out.zip](https://github.com/mysteriumnetwork/node/files/9174437/goroutine.out.zip)

**Comment by Snawoot** [comment] 2022-07-23 18:52
it created about 13000 goroutines and they consume a lot of memory:

![pprof screenshot](https://user-images.githubusercontent.com/3524671/180619020-7b634ee3-958a-4e44-868d-920b47c851dc.png)

root cause is in server side events code.

**Comment by Snawoot** [comment] 2022-07-23 18:55
goroutines hang sending into this channel: https://github.com/mysteriumnetwork/node/blob/ead5fcd909060933e3ea22438b30138ee9a1d625/tequilapi/endpoints/sse_handler.go#L200

**Comment by etherunit** [comment] 2022-07-24 10:08
relates to https://github.com/mysteriumnetwork/node/issues/5244

**Comment by Snawoot** [comment] 2022-07-26 06:23
Fixed in 1.9.7.

**Closed by Snawoot** 2022-07-26 06:23 UTC
Labels: bug, major
