### ISSUE TITLE
need a way to identify provider version

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#2218] opened 2020-05-12 14:00 UTC
From time to time certain upgrades are being made to the network, yet some providers update their versions at different speeds (sometimes this is very good, as older client versions can be supported).

For instance, after 0.31 upgrade, most providers (I'd assume those who upgraded to 0.31) fail to be connected to by older than 0.31 version.
It would be nice in theory, that both providers and clients would upgrade at the same time, but in practice this is impossible (for instance even play store would review and update the app in 7+ days).

I propose to include provider version when returning provider signature at /proposals so clients can filter out incompatible provider versions.

**Comment by anjmao** [comment] 2020-05-12 15:21
Yes we talked about this issue few times. Including version is not secure but instead proposal can contain compatibility level which could be increased manually.

**Comment by cvl** [comment] 2020-05-13 06:31
I assume you're saying those levels would be set by node developers (i.e. you guys), and not providers, correct? Sounds like a good way to solve this.

**Comment by zolia** [comment] 2020-05-14 08:58
duplicate of #1999

**Closed by zolia** 2020-05-14 08:58 UTC
Labels: component:node
