### ISSUE TITLE
testnet3 - registration taking more than 5 mins 

### ISSUE THREAD

**Issue by endosym1** [mysteriumnetwork/node#3667] opened 2021-07-25 03:41 UTC
installed the testnet3 using docker and opened. http://127.0.0.1:4449/

![Screenshot 2021-07-25 at 9 10 02 AM](https://user-images.githubusercontent.com/87921704/126887003-ef69b1b2-61a8-4de8-acd8-b7f882b98a85.png)

Adding more info -- 

» status 
[INFO] Status: NotConnected
[INFO] SID: 
[INFO] IP: 36.255.87.4
[INFO] Location: Karnataka, IN (residential - Deshkal Network)
» nat
[INFO] NAT traversal status: "not_finished"
» healthcheck
[INFO] Uptime: 16m39.364238299s
[INFO] Process: 1
[INFO] Version: 0.52.0-1branch-testnet3-b-1
[INFO] Branch: testnet3-build. Build id: 342417719. Commit: c3b528ba
» identities get 0xbf36415813d6be55e932f6ef3ad5061452b771db
[INFO] Registration Status: Unregistered
[INFO] Channel address: 0x9d88041B84960D82CB5A0c56530B7dDD15081e3b
[INFO] Balance: 0.000000
[INFO] Earnings: 0.000000
[INFO] Earnings total: 0.000000
»

**Comment by endosym1** [comment] 2021-07-25 04:12
registered after few reboots -- 

`2021-07-25T04:01:56.705 DBG config/config.go:196 > Returning default value chain-id:80001

2021-07-25T04:01:56.705 DBG config/config.go:196 > Returning default value chain-id:80001


2021-07-25T04:01:57.214 ERR identity/registry/provider_registrar.go:249 > Registration failed for provider "0xbf36415813d6be55e932f6ef3ad5061452b771db" error="server response invalid: 400 Bad Request (https://testnet3-transactor.mysterium.network/api/v1/identity/register){\"error\":\"transactor requires at least 2595310859001572 fee\"}"

2021-07-25T04:01:57.214 ERR identity/registry/provider_registrar.go:158 > Could not complete registration for provider "0xbf36415813d6be55e932f6ef3ad5061452b771db". Will retry. Retry 0 of 10 error="could not register identity on BC: server response invalid: 400 Bad Request (https://testnet3-transactor.mysterium.network/api/v1/identity/register){\"error\":\"transactor requires at least 2595310859001572 fee\"}"


2021-07-25T04:01:58.636 ERR ui/server.go:106 > Failed to start local discovery service error="Could not determine host IP addresses for f34eacbe3590."


2021-07-25T04:02:16.476 ERR session/pingpong/consumer_balance_tracker.go:166 > Could not recover Grand Total Promised error="could not request consumer data from hermes: resource not found"


2021-07-25T04:02:18.028 ERR session/pingpong/consumer_balance_tracker.go:397 > Could not get consumer channel error="no contract code at given address"


2021-07-25T04:02:18.276 DBG eventbus/event_bus.go:81 > Published topic="balance_change" event={Identity:{Address:0xbf36415813d6be55e932f6ef3ad5061452b771db} Previous:+0 Current:+0}


2021-07-25T04:02:18.519 ERR session/pingpong/consumer_balance_tracker.go:243 > could not subscribe to channel balance events error="Too many subscriptions open. Try closing idle WS connections."


2021-07-25T04:02:25.359 INF pilvytis/order_status_tracker.go:126 > Pausing order status tracking


2021-07-25T04:03:23.120 DBG mmn/client.go:79 > Updating beneficiary in MMN: {Beneficiary:0x46264C8b03dd3AD3269b08f3C0834ABa80a39F3e Identity:0xbf36415813d6be55e932f6ef3ad5061452b771db}


2021-07-25T04:03:23.335 DBG config/config.go:196 > Returning default value chain-id:80001


2021-07-25T04:03:24.472 ERR tequilapi/endpoints/transactor.go:285 > Failed identity registration request for ID: 0xbf36415813d6be55e932f6ef3ad5061452b771db, &{ReferralToken:<nil>} error="server response invalid: 400 Bad Request (https://testnet3-transactor.mysterium.network/api/v1/identity/register){\"error\":\"transactor requires at least 2595310859001572 fee\"}"


2021-07-25T04:04:57.091 DBG config/config.go:196 > Returning default value chain-id:80001


2021-07-25T04:04:58.470 INF identity/registry/provider_registrar.go:200 > Provider "0xbf36415813d6be55e932f6ef3ad5061452b771db" not registered on BC, will check if elgible for auto-registration


2021-07-25T04:04:58.471 DBG config/config.go:196 > Returning default value chains.1.chainID:5


2021-07-25T04:04:58.856 DBG config/config.go:196 > Returning default value chain-id:80001

2021-07-25T04:04:58.856 DBG config/config.go:196 > Returning default value chains.2.chainID:80001


2021-07-25T04:04:58.856 DBG config/config.go:196 > Returning default value chain-id:80001


2021-07-25T04:04:58.857 DBG config/config.go:196 > Returning default value chain-id:80001


2021-07-25T04:04:59.674 ERR identity/registry/provider_registrar.go:249 > Registration failed for provider "0xbf36415813d6be55e932f6ef3ad5061452b771db" error="server response invalid: 400 Bad Request (https://testnet3-transactor.mysterium.network/api/v1/identity/register){\"error\":\"transactor requires at least 2595310859001572 fee\"}"

2021-07-25T04:04:59.674 ERR identity/registry/provider_registrar.go:158 > Could not complete registration for provider "0xbf36415813d6be55e932f6ef3ad5061452b771db". Will retry. Retry 1 of 10 error="could not register identity on BC: server response invalid: 400 Bad Request (https://testnet3-transactor.mysterium.network/api/v1/identity/register){\"error\":\"transactor requires at least 2595310859001572 fee\"}"


2021-07-25T04:06:50.234 DBG mmn/client.go:79 > Updating beneficiary in MMN: {Beneficiary:0x46264C8b03dd3AD3269b08f3C0834ABa80a39F3e Identity:0xbf36415813d6be55e932f6ef3ad5061452b771db}


2021-07-25T04:06:51.181 DBG config/config.go:196 > Returning default value chain-id:80001


2021-07-25T04:06:54.441 DBG eventbus/event_bus.go:81 > Published topic="transactor_identity_registration" event={RegistryAddress:0xDFAB03C9fbDbef66dA105B88776B35bfd7743D39 HermesID:0x7119442C7E627438deb0ec59291e31378F88DD06 Stake:+0 Fee:+2595310859001572 Beneficiary:0x9d88041b84960d82cb5a0c56530b7ddd15081e3b Signature:0x2598ee33a0b4eb3633cf8ff70973a6b4ea417e65a45fa085e91a8087e3a10fba73a043d4182e75280e7ae7c43cae0cb4f038c36bad1408c5d65da3fe266bd0791c Identity:0xbf36415813d6be55e932f6ef3ad5061452b771db ChainID:80001}


2021-07-25T04:06:54.442 DBG eventbus/event_bus.go:81 > Published topic="registration_event_topic" event={ID:{Address:0xbf36415813d6be55e932f6ef3ad5061452b771db} Status:InProgress ChainID:80001}

2021-07-25T04:06:54.447 INF identity/registry/registry_contract.go:232 > Waiting on identities 0xBf36415813d6BE55e932f6EF3Ad5061452b771DB hermes 0x7119442C7E627438deb0ec59291e31378F88DD06

2021-07-25T04:06:54.448 DBG core/discovery/discovery.go:161 > Registration event received for 0xbf36415813d6be55e932f6ef3ad5061452b771db

2021-07-25T04:06:54.448 INF core/discovery/discovery.go:175 > Received status InProgress ignoring

2021-07-25T04:06:54.450 DBG session/pingpong/hermes_promise_settler.go:265 > Ignoring event InProgress for provider {"0xbf36415813d6be55e932f6ef3ad5061452b771db"}


2021-07-25T04:06:54.889 DBG eventbus/event_bus.go:81 > Published topic="registration_event_topic" event={ID:{Address:0xbf36415813d6be55e932f6ef3ad5061452b771db} Status:RegistrationError ChainID:80001}


2021-07-25T04:06:54.901 DBG core/discovery/discovery.go:161 > Registration event received for 0xbf36415813d6be55e932f6ef3ad5061452b771db

2021-07-25T04:06:54.901 INF core/discovery/discovery.go:172 > Cancelled identity registration

2021-07-25T04:06:54.902 ERR identity/registry/registry_contract.go:248 > Could not register to identity events error="Too many subscriptions open. Try closing idle WS connections."


2021-07-25T04:06:54.897 DBG core/location/oracle_resolver.go:64 > Detecting with oracle resolver


2021-07-25T04:06:54.910 DBG session/pingpong/hermes_promise_settler.go:265 > Ignoring event RegistrationError for provider {"0xbf36415813d6be55e932f6ef3ad5061452b771db"}


2021-07-25T04:06:55.545 DBG eventbus/event_bus.go:81 > Published topic="location-update-event" event={IP:36.255.87.4 ASN:132559 ISP:Deshkal Network Continent:AS Country:IN City:Karnataka IPType:residential}


2021-07-25T04:06:56.474 INF session/pingpong/pricing.go:160 > pricing info loaded


2021-07-25T04:07:59.553 DBG config/config.go:196 > Returning default value chain-id:80001


2021-07-25T04:08:00.125 INF identity/registry/provider_registrar.go:196 > Provider "0xbf36415813d6be55e932f6ef3ad5061452b771db" already registered on bc, skipping

2021-07-25T04:08:00.126 DBG eventbus/event_bus.go:81 > Published topic="registration_event_topic" event={ID:{Address:0xbf36415813d6be55e932f6ef3ad5061452b771db} Status:Registered ChainID:80001}

2021-07-25T04:08:00.126 DBG core/discovery/discovery.go:161 > Registration event received for 0xbf36415813d6be55e932f6ef3ad5061452b771db

2021-07-25T04:08:00.128 INF core/discovery/discovery.go:169 > Identity registered, proceeding with proposal registration


2021-07-25T04:08:00.129 INF session/pingpong/hermes_promise_settler.go:268 > Identity registration event received for provider {"0xbf36415813d6be55e932f6ef3ad5061452b771db"}`

**Comment by vkuznecovas** [comment] 2021-07-29 07:27
This is caused by instability of the matic nodes we're using for mumbai testnet3. We've got a fix for that in mind and it's something that I'm working on right now. I'll close this issue, you can track progress of #3683 instead.

**Closed by vkuznecovas** 2021-07-29 07:27 UTC
Labels: bug, testnet3
