### ISSUE TITLE
[android, bug] stuck in disconnecting state, need to restart phone + provider is overcharging error

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3256] opened 2021-03-29 15:06 UTC
**Describe the bug**
- Connect to provider (0x751f1f5bc153872c1bc38c37789069480e5fb8d1)
- Try to disconnect. Node is stuck in "disconnecting" state. App hangs, can't do anything. VPN is connected to provider. Need to restart phone.

Logs also output the following error:  Payment error error="invoice not valid: provider is overcharging"

Possible hack attempt?

Tried the same provider 2 times, both resulted in the same behavior.

Logs:
[mysterium-node 30.log](https://github.com/mysteriumnetwork/node/files/6222660/mysterium-node.30.log)

**Environment (please complete the following information):**
 - Node version: 0.42.1
 - OS: Android 9

**Comment by vkuznecovas** [comment] 2021-03-29 15:10
Provider has an insane pricing set on his end, therefore the client rejects him. This is the intended behaviour. A better user experience for this part is coming soon™.

As far as being stuck in disconnect, this is a duplicate of #3254 as any sort of session termination does not get handled gracefully. 

I'm therefore closing this as it's a duplicate.

**Closed by vkuznecovas** 2021-03-29 15:10 UTC
Labels: bug

**Comment by cvl** [comment] 2021-03-29 15:27
Hmm, don't think this is the case (regarding the pricing), rather more likely it's a hack attempt.

- I'm filtering out high priced providers.
- Also, afaik the price is settled BEFORE the transaction, the price doesn't change while being connected.
- Consumer node doesn't disconnect on its own (i.e. it doesn't see that something is wrong).
- This happens only when I click disconnect manually. It just doesn't disconnect.

**Comment by vkuznecovas** [comment] 2021-03-29 16:31
> I'm filtering out high priced providers.

This providers price is 2x the current network rate, so you've probably filtered him at another date.

> Also, afaik the price is settled BEFORE the transaction, the price doesn't change while being connected.

The price is only announced. An actor in the network can publish a proposal with any price. This, however, does not guarantee that he'll be basing his calculations on this price(as the software is open source, anyone can modify it easily). Therefore both parties(consumer and provider) keep track of the price and the current bandwidth/time in the session, recalculating and re-checking on every checkpoint. If one party is unhappy, the session gets destroyed. This is exactly what happens here.

> Consumer node doesn't disconnect on its own (i.e. it doesn't see that something is wrong). 

This is exactly the same issue that happens on #3254. It does see that something is wrong(i.e. you can see the error) yet the node "hangs", waiting for input from user.


> This happens only when I click disconnect manually. It just doesn't disconnect.

See above

**Comment by cvl** [comment] 2021-03-30 08:10
Thanks, that was obviously the hack attempt then. I've banned the node.
