### ISSUE TITLE
non-payment after???

### ISSUE THREAD

**Issue by shackleford92** [mysteriumnetwork/node#4890] opened 2022-03-16 19:13 UTC
**Describe the bug**
raspberry pi4 64bit running bullseye
bashd an update script via ssh
saw that what i believed to be relevant packages get updated
waited for no live sessions to be active
rebooted over ssh
i then didnt recieve payment for the sessions over the next 4 days
i reached out to support who instructed me to
 sudo journalctl -u mysterium.service
which still returns 
-- Journal begins at Thu 2022-02-03 22:35:01 EST, ends at Wed 2022-03-16 14:19:>
-- No entries --
the log seems to have a ~30day cap as when i reached out to support it said 1/31 i believe
im updating from Hit:5 http://ppa.launchpad.net/mysteriumnetwork/node/ubuntu focal InRelease
i have 40 pages of logs in the gui for unpaid traffic copy pasted from the gui here https://textuploader.com/t159e

a hard reboot eventually resolved it

i can try and pull the relevant system logs if an individual wiser than i would direct me how to

**To Reproduce**
1. Go to '...'my bash script to update    
sudo pihole disable
#update maldet
sudo maldet -u
#update clousdflared keep config
wget -N  https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64
sudo systemctl stop cloudflared
sudo cp ./cloudflared-linux-arm64 /usr/local/bin/cloudflared
sudo chmod +x /usr/local/bin/cloudflared
sudo systemctl start cloudflared
cloudflared -v
#update errythang
sudo -- sh -c 'apt-get update; apt-get upgrade -y; apt-get dist-upgrade -y; apt-get autoremove -y; apt-get autoclean -y'
#fix shit
sudo apt install -f
#update pihole
sudo pihole -up
#turn pihole back on
sudo pihole enable

then sudo reboot
3. proceed to not be paid for 4 days and >5gb traffic
4. have your total earnings and unsettled funds zerod in the gui despite logs showing a 3.98 settlement for a previous 5 myst being accrued
5. be unable to withdraw said myst from the gui returning a wallet error?

**Expected behavior**
it to continue functioning properly as it had and currently is

**Screenshots**
![image](https://user-images.githubusercontent.com/84883724/158664235-f05fa54d-56fa-45a3-9395-f3db1f3995dc.png)
it sat at 4.09 showing 0 payout for consumed traffic for the duration of this as shown here https://textuploader.com/t159e
![image](https://user-images.githubusercontent.com/84883724/158668653-b6796f4b-43d8-49f9-ad7a-bb584cfa5910.png)
if i could see the chat history with support, there were screenshots from that period of time where everything but my balance was 0.00

**Environment (please complete the following information):**
0xf6c481f1b60c686cc690dcc108071b08b832a888
1.4.1
Debian GNU/Linux 11 (bullseye)
 - Node version: [1.4.1]
 - OS: [e.g. raspbian bullseye, debian 11]
 - Your identity (if applicable): [+] 0xf6c481f1b60c686cc690dcc108071b08b832a888
 - Payment (top-op) reference (if applicable): 

**Additional context**
40pages of the only logs i can see:   https://textuploader.com/t159e
im just seeing if i could be compensated as issac from support suggested may be possible when he pointed me here
i assume this being crypto theres PoW in the blockchain evidencing this traffic and hopefully the lack of payment i didnt receive

**Comment by etherunit** [comment] 2022-03-18 05:27
@Guillembonet Should this be addressed in 1.4.1 node version?

**Comment by Guillembonet** [comment] 2022-03-18 14:13
so this is solved now? it might have been caused by polygon being down for a long time and the node not recovering after that

**Comment by shackleford92** [comment] 2022-03-19 13:03
it explicitly occurred after a normal reboot. everything else chugged along fine. this was the first two sessions after that boot, i dont know if it coincides with the network being down.

India
00:05:37
10/03/2022, 13:09:30
0.0000000 MYST
3.46 MB
652eb7fe
Nigeria
00:00:46
10/03/2022, 13:00:11
0.0000000 MYST
698.68 KB
f7201e14

**Comment by Guillembonet** [comment] 2022-03-21 07:27
It looks like it might be from around that time, I'll close it, if you see this issue or any other again please report it. Thanks!

**Closed by Guillembonet** 2022-03-21 07:27 UTC
Labels: bug, major
