### ISSUE TITLE
Node withdrawal not reflected on metamask wallet

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/node#5440] opened 2022-09-16 09:21 UTC
**Describe the bug**
Sent Myst from node to MetaMask but not showing up on balance 

<img width="1227" alt="Screenshot 2022-09-16 at 06 20 47" src="https://user-images.githubusercontent.com/84313603/190604163-755ce1ec-61d9-45d6-9fc0-b6c7fca896c7.png">
<img width="1400" alt="Screenshot 2022-09-16 at 06 21 02" src="https://user-images.githubusercontent.com/84313603/190604175-0df6167f-1525-4c12-9832-edffdb27ddb4.png">

**Comment by etherunit** [comment] 2022-09-17 05:32
Make sure that it's correctly added. The majority of such issues are caused by an incorrect Polygon/MYST token setup.
https://docs.mysterium.network/for-node-runners/how-to-setup-polygon-myst-on-metamask

**Comment by etherunit** [comment] 2022-09-21 05:26
@isaackielma Please suggest the above info and feel free to reopen/get back to me if it wont help.
I'll close this for now.

**Closed by etherunit** 2022-09-21 05:26 UTC
Labels: bug
