### ISSUE TITLE
Avado wallet doesn't appear on MMN.

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3048] opened 2021-01-25 06:24 UTC
**Describe the bug**
Provider set his ETH wallet address on Avado console but it's not being reflected in MMN. Showing as "Ineligible". Wallet address field is empty there.

<img width="1073" alt="Screenshot 2021-01-25 at 08 19 56" src="https://user-images.githubusercontent.com/60128746/105668631-6383c080-5ee6-11eb-8c47-9b14d8163e48.png">
<img width="756" alt="Screenshot 2021-01-25 at 08 22 31" src="https://user-images.githubusercontent.com/60128746/105668667-7c8c7180-5ee6-11eb-8e95-3e848ab98687.png">

**Comment by vkuznecovas** [comment] 2021-01-25 08:23
This is most likely caused by them using the payout address endpoint.

**Comment by frankhmurray** [comment] 2021-01-25 14:16
So is this a problem with Avado? How can this get resolved? In my Mysterium account it says no wallet has been entered and not sure how to do this. I sent the public key to your CS team and have heard nothing.

**Comment by frankhmurray** [comment] 2021-01-25 14:22
<img width="555" alt="Screen Shot 2021-01-25 at 9 21 42 AM" src="https://user-images.githubusercontent.com/3697588/105718073-db55e900-5eee-11eb-8d41-4a75732b365b.png">

**Comment by frankhmurray** [comment] 2021-01-25 14:23
What's up with this? in Avado it clearly shows that I submitted a wallet, but your system is not picking it up...

**Comment by vkuznecovas** [comment] 2021-01-26 13:16
We're currently working to get this resolved with Avado.

**Comment by vkuznecovas** [comment] 2021-01-28 07:41
@frankhmurray could you please upgrade your avado node and try again now?

**Comment by vkuznecovas** [comment] 2021-02-02 12:20
Closing this as Avado have updated the node version to the latest one.

**Closed by vkuznecovas** 2021-02-02 12:20 UTC
Labels: avado, bug
