### ISSUE TITLE
DNS fails and returns nothing on Windows app

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#2422] opened 2020-06-30 06:38 UTC
**Describe the bug**
Can connect to certain providers but internet is not working while connected. 

P.S. When connecting to the same node from Android app or CLI, everything works fine.

**To Reproduce**
1. Open MysteriumVPN app for Windows
2. Select Residential node: 0x409b5c902d26d4c5250dce8cbd574bd0cbe2b8cb
3. This provider fail to resolve DNS. Internet is not working while connected.

**Expected behavior**
DNS is consistently resolved.

**Screenshots**
![Myst](https://user-images.githubusercontent.com/60128746/86091843-3e94af80-bab5-11ea-9003-d06e08d7b93d.jpg)

**Environment (please complete the following information):**
 - Node version: 0.35
 - OS: Windows10
 - Desktop app version 2.3.0

**Additional context**
main.log
```
[2020-06-29 19:00:41.407] [info] Connecting to the supervisor...
[2020-06-29 19:00:43.543] [info] Connected to:  \\.\pipe\mystpipe
[2020-06-29 19:09:33.141] [info] Checking for update
[2020-06-29 19:09:36.917] [info] Connecting to the supervisor...
[2020-06-29 19:09:36.920] [info] Connected to:  \\.\pipe\mystpipe
[2020-06-29 19:09:37.525] [info] Bundled supervisor version: 0.35.0-rc0

[2020-06-29 19:09:37.527] [info] Server: ok: 0.35.0-rc0

[2020-06-29 19:09:37.529] [info] Running supervisor version: 0.35.0-rc0

[2020-06-29 19:09:37.530] [info] Running supervisor version is compatible, skipping the upgrade
[2020-06-29 19:09:38.687] [info] Update for version 2.3.0 is not available (latest version: 2.1.1, downgrade is disallowed).
[2020-06-29 22:09:46.508] [info] Connecting to the supervisor...
[2020-06-29 22:09:46.510] [info] Connected to:  \\.\pipe\mystpipe
[2020-06-29 22:09:46.560] [info] Bundled supervisor version: 0.35.0-rc0

[2020-06-29 22:09:46.562] [info] Server: ok: 0.35.0-rc0

[2020-06-29 22:09:46.565] [info] Running supervisor version: 0.35.0-rc0

[2020-06-29 22:09:46.566] [info] Running supervisor version is compatible, skipping the upgrade
[2020-06-29 22:09:46.685] [info] myst process exited with code 1
[2020-06-30 01:09:52.485] [info] Connecting to the supervisor...
[2020-06-30 01:09:52.486] [info] Connected to:  \\.\pipe\mystpipe
[2020-06-30 01:09:52.539] [info] Bundled supervisor version: 0.35.0-rc0

[2020-06-30 01:09:52.542] [info] Server: ok: 0.35.0-rc0

[2020-06-30 01:09:52.543] [info] Running supervisor version: 0.35.0-rc0

[2020-06-30 01:09:52.544] [info] Running supervisor version is compatible, skipping the upgrade
[2020-06-30 01:09:52.689] [info] myst process exited with code 1
[2020-06-30 08:59:43.349] [info] Connecting to the supervisor...
[2020-06-30 08:59:43.436] [info] Connected to:  \\.\pipe\mystpipe
[2020-06-30 08:59:46.953] [info] Bundled supervisor version: 0.35.0-rc0

[2020-06-30 08:59:46.954] [info] Server: ok: 0.35.0-rc0

[2020-06-30 08:59:46.955] [info] Running supervisor version: 0.35.0-rc0

[2020-06-30 08:59:46.955] [info] Running supervisor version is compatible, skipping the upgrade
[2020-06-30 08:59:49.025] [info] myst process exited with code 1
```

renderer.log
```
[2020-06-30 08:59:23.719] [error] [sse error] { isTrusted: true }
[2020-06-30 08:59:23.821] [error] [sse error] { isTrusted: true }
[2020-06-30 08:59:23.827] [error] Healthcheck failed: Network Error (path="healthcheck")
[2020-06-30 08:59:27.344] [info] Another healthcheck is in progress, skipping
[2020-06-30 08:59:28.978] [info] Using config: {"desktop":{"terms-agreed":{"at":"2020-06-20T18:18:42.294Z","version":"0.0.27"}}}
[2020-06-30 08:59:29.047] [error] Could not get proposals Request failed with status code 500 (path="proposals")
[2020-06-30 08:59:35.343] [info] Another healthcheck is in progress, skipping
[2020-06-30 08:59:37.343] [info] Another healthcheck is in progress, skipping
[2020-06-30 08:59:39.343] [info] Another healthcheck is in progress, skipping
[2020-06-30 08:59:41.343] [info] Another healthcheck is in progress, skipping
[2020-06-30 08:59:42.769] [error] Could not get proposals timeout of 5000ms exceeded (path="proposals")
[2020-06-30 08:59:43.343] [info] Another healthcheck is in progress, skipping
[2020-06-30 08:59:43.345] [error] Healthcheck failed: timeout of 10000ms exceeded (path="healthcheck")
[2020-06-30 08:59:45.344] [info] Daemon is starting, skipping healthcheck
[2020-06-30 08:59:47.353] [info] Using config: {"desktop":{"terms-agreed":{"at":"2020-06-20T18:18:42.294Z","version":"0.0.27"}}}
[2020-06-30 09:00:35.343] [info] Another healthcheck is in progress, skipping
[2020-06-30 09:00:39.344] [info] Another healthcheck is in progress, skipping
[2020-06-30 09:00:43.449] [error] Could not connect timeout of 30000ms exceeded (path="connection")
[2020-06-30 09:00:48.468] [error] Could not get proposals Request failed with status code 500 (path="proposals")
[2020-06-30 09:00:51.343] [info] Another healthcheck is in progress, skipping
[2020-06-30 09:00:51.716] [error] Failed to lookup location Request failed with status code 503 (path="connection/location")
[2020-06-30 09:00:55.344] [info] Another healthcheck is in progress, skipping
[2020-06-30 09:10:25.344] [info] Another healthcheck is in progress, skipping
[2020-06-30 09:10:25.501] [error] Failed to lookup location Request failed with status code 503 (path="connection/location")
```

node.logs:
https://my.mysterium.network/admin/issues/download/731
user report:
https://github.com/mysteriumnetwork/node-user-reports/issues/731

**Comment by chompomonim** [comment] 2020-07-07 11:15
Duplicate of #2387

**Closed by chompomonim** 2020-07-07 11:15 UTC
Labels: bug, component:desktop, system:windows
