### ISSUE TITLE
Documentation layout and its production workflow

### ISSUE THREAD

**Issue by zolia** [mysteriumnetwork/node#1604] opened 2020-01-31 08:10 UTC
We need to decide how to proceed further with building and maintaining documentation properly.
Currently our documentation is out of date or even incorrect, spreaded across multiple sources, visually not appealing and badly structured. 

We need documentation for: 
 - node runners
 - consumers
 - developers 
 
We should validate documentation by testng what has been written either by developers themselves or by requesting tests from our testers. This can be in form of a separate issue, but it has to be resolved before feature changes affecting documentation could be merged.

Documentation texts should be cross-checked by peers for style and correctness too. 

Some IMHO good examples of API doc: https://stripe.com/docs/api
Some good example of guild like doc: https://stripe.com/docs/terminal/sdk/android

Need your thoughts on how to automate documentation generation, how to make it easily editable, how to request external contributors to help fix our grammar and clarity.

**Comment by soffokl** [comment] 2020-01-31 08:28
The current http://docs.mysterium.network/ uses https://readthedocs.org/. 

It supports versions(every version can have own docs), custom themes and can be edited as a simple markdown with PRs and review. Anyone, including outside contributors, can create PRs with changes.

Take a look at how this can appear with the right content: https://sphinx-rtd-theme.readthedocs.io/en/stable/

I believe that the problem with documentation is that no one is writing it. And placing it to another space will not resolve the problem.

My suggestion is to start writing documentation. 
Never close the issue until you posted a link to the updated documentation or described why it's not required. Adding some context to the issues will help here.

**Comment by etherunit** [comment] 2020-01-31 11:24
I agree with the comment above. It is so important to update the documentation with at least support-level understandable terminology once the issue is fixed. Moving forward, this will enable the possibility to easier reproduce test cases while dealing with node issues + I will be able to rewrite those documents into manuals/guides and post them in our help section which is connected to intercom (our main support channel)

**Comment by chompomonim** [comment] 2020-02-12 19:10
Types of documentation:
- Text documentation
- Q&A types of documentation
- Forums 

- Tutorial type of docs:
  - Text
  - Video

Possible separation
==============
- Platform developers
   - Main tech context (the structure, etc.)
   - Contribution documentation (how to contribute)
   - API

- Users documentation
   - Node runner guides
   - Business consumer guides
   - End users (e.g. desktop app) guides
   - Q&A thing (how to debug, resolve an issue)

- App developer
   - SKD
   - Tutorial

Questions to answer
==============
Provider / Node runner:
 - What is Mysterium and why to become node runner
 - FAQ:      
      - Is it save to run a node
      - Is it legal to run node 
- Guides:
  - Hot to run a node (Linux, Docker, RPi, Windows, MacOSX)
  - How to upgrade your node

**Closed** 2021-01-19 07:36 UTC
Labels: documentation
