### ISSUE TITLE
Hermes error

### ISSUE THREAD

**Issue by Stillbadatlinux** [mysteriumnetwork/node#4716] opened 2022-02-02 13:33 UTC
**Describe the bug**

**To Reproduce**
1. Go to ‘withdraw’
2. Click on 'withdraw’
3. Then when I go to polygonscan I will see error Hermes

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - Node version: [1.70]
 - OS: [raspbian buster]
 - Your identity 0x88ee45499bfb9c606d117bf3178796cf3c635df8
 - Payment (top-op) reference (if applicable): [0xF16606b11A77a525A6DD2F26355A18B8B0B5DEEc]

**Additional context**
This was my last transaction 0x6280f1110da943fe61d1880af6a0cfdda3acd147ce725ff01a5fd719a187cd1b

**Comment by tomasmik** [comment] 2022-02-03 14:14
Duplicate of:
* https://github.com/mysteriumnetwork/node/issues/4720
* https://github.com/mysteriumnetwork/node/issues/4679

**Closed by tomasmik** 2022-02-03 14:14 UTC
Labels: bug, duplicate
