### ISSUE TITLE
How would I go about using this on windows?

### ISSUE THREAD

**Issue by schlarmanorg** [MysteriumNetwork/node#119] opened 2018-01-25 23:05 UTC
I am just trying to test it out, I already have a node up and I am wanting to try the client side. I am using windows 10

**Comment by Waldz** [comment] 2018-01-26 07:08
Currently we did not tested on Windows yet.
Primary goals is OSX, then Linux, then Windows.
Duplicate of #3

**Comment by Waldz** [comment] 2018-01-26 07:08
Duplicate of #3

**Closed by Waldz** 2018-01-26 07:08 UTC
Labels: duplicate, question
