### ISSUE TITLE
Payment engine error

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#3351] opened 2021-05-04 04:22 UTC
Provider id: 0x2f34b5448fd2292bd8760dd23add02f900761995
OS: Alpine Linux v3.12
Node version: 0.45.0
ChannelID: 0xdae46ab208a40488baf216c4818d35471d53c8a1d6733f11df037d499ee454fe

```
2021-05-03T12:50:50.303 DBG session/pingpong/price_calculator.go:72 > Calculated price 6470595667595905. Time component: 4.8528551202591668768e+14, data component: 5.9853101555699890215e+15
2021-05-03T12:50:50.304 ERR core/service/session_manager.go:285 > Payment engine error error="sending of invoice failed: did not sent a new exchange message"
2021-05-03T12:50:50.304 INF services/wireguard/service/service_unix.go:178 > Cleaning up session d33af44c-4f5a-4699-8702-6b34818659e8
panic: close of closed channel

goroutine 2511688 [running]:
github.com/mysteriumnetwork/node/services/wireguard/service.statsPublisher.stop(...)
/go/src/github.com/mysteriumnetwork/node/services/wireguard/service/stats_publisher.go:69
github.com/mysteriumnetwork/node/services/wireguard/service.(*Manager).ProvideConfig.func1()
/go/src/github.com/mysteriumnetwork/node/services/wireguard/service/service_unix.go:183 +0x20a
github.com/mysteriumnetwork/node/core/service.(*SessionManager).providerService.func1(0x0, 0x17134a9)
/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:309 +0x28
github.com/mysteriumnetwork/node/core/service.(*Session).Close.func1()
/go/src/github.com/mysteriumnetwork/node/core/service/session.go:62 +0x1fc
sync.(*Once).doSlow(0xc00179d698, 0xc000713f68)
/usr/local/go/src/sync/once.go:66 +0xe3
sync.(*Once).Do(...)
/usr/local/go/src/sync/once.go:57
github.com/mysteriumnetwork/node/core/service.(*Session).Close(0xc00179d520)
/go/src/github.com/mysteriumnetwork/node/core/service/session.go:54 +0x6a
github.com/mysteriumnetwork/node/core/service.(*SessionManager).paymentLoop.func2(0x1e398c0, 0xc001795200, 0xc00179d520)
/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:286 +0xb1
created by github.com/mysteriumnetwork/node/core/service.(*SessionManager).paymentLoop
/go/src/github.com/mysteriumnetwork/node/core/service/session_manager.go:282 +0x29a
```

**Comment by tomasmik** [comment] 2021-05-04 05:42
This is sort of a duplicate of https://github.com/mysteriumnetwork/node/issues/3310

**Closed** 2021-05-05 08:55 UTC
Labels: bug
