### ISSUE TITLE
interface bug

### ISSUE THREAD

**Issue by dddavid51** [mysteriumnetwork/node#5491] opened 2022-09-28 20:25 UTC
Hello,
I wanted to report a bug when I want to change the pickup address and I click on the little pen the window closes.
I have the same problem on bug report when I click on the email address the window closes too.
Sincerely,
David

0x522a4e1c061ebfbb8b1859e110f413d41817f4e8
1.17.3

**Comment by etherunit** [comment] 2022-09-29 05:35
Duplicate of https://github.com/mysteriumnetwork/node/issues/5469

**Comment by etherunit** [comment] 2022-09-29 05:36
@Ayse-AK Any updates on this one?

**Comment by Ayse-AK** [comment] 2022-09-29 05:56
@etherunit it's on our to-do list.

**Closed** 2022-10-04 12:29 UTC
Labels: bug

**Comment by sayembara** [comment] 2022-10-05 12:16
I'm still having the above issue today, unable to change the withdraw address. I will test again after a day or two, assuming the update requires some days to take effect.

**Comment by Ayse-AK** [comment] 2022-10-05 12:49
@sayembara Please make sure that you are using the latest version

**Comment by sayembara** [comment] 2022-10-05 22:24
> @sayembara Please make sure that you are using the latest version

Yes, using latest Mysterium Node launcher 1.18.3. But the issue is at http://localhost:4449/#/transactions ("Settle Now"), unable to change the withdraw wallet address. Please share the link to update this web interphase. Thanks a lot.

**Comment by sayembara** [comment] 2022-10-10 11:01
Ok, today I tried and confirmed the address could be changed. Thanks for the quick update. Issue closed.
