### ISSUE TITLE
Myst tokens not showing

### ISSUE THREAD

**Issue by mayutj17** [mysteriumnetwork/node#4861] opened 2022-03-09 10:08 UTC
this is my node. which shows i have earned some tokens. 
![image](https://user-images.githubusercontent.com/101254355/157419758-1f921ded-5112-497f-8790-aaf7fb99f339.png)

but dash board shows this.

![image](https://user-images.githubusercontent.com/101254355/157419986-e2f30f8f-79cb-43f0-878b-c1e1594a0935.png)

what is the issue?

**Comment by etherunit** [comment] 2022-03-09 10:50
@Guillembonet Does the auto fix is in place or we still fix them manually one by one?

**Comment by mamushiraz** [comment] 2022-03-11 08:17
Having the same problem. Day before I have 2.7+ MYST and its missing now. Not just the balance missing but the current rewards also showing 0.00 MYST
![mysteruim03](https://user-images.githubusercontent.com/59684117/157828698-60b4cae9-bbcb-4741-a976-ee9a20de9406.JPG)
![mysteruim04](https://user-images.githubusercontent.com/59684117/157828727-15016231-d2f0-42da-b48c-8939f02db1c6.JPG)
![mysteruim01](https://user-images.githubusercontent.com/59684117/157828782-6b295186-eb36-48e7-a0d4-299b1569a11d.JPG)
![mysteruim02](https://user-images.githubusercontent.com/59684117/157828793-e9c2978e-ae15-4b64-93b9-e241bb02129f.JPG)

**Comment by Guillembonet** [comment] 2022-03-14 08:45
is it still ongoing? everything seems normal, the last message you posted was when polygon was down so there was no data. It should be fine now, let me know if its not!

**Comment by mayutj17** [comment] 2022-03-14 09:22
Still the same issue

**Comment by Guillembonet** [comment] 2022-03-15 08:18
hey, can you try restarting the node, I'm seeing your node is doing requests to our Hermes and earning as intended, maybe it's a leftover issue from polygon being down a few days ago

**Comment by mayutj17** [comment] 2022-03-15 09:42
Ok sure

**Comment by Guillembonet** [comment] 2022-03-15 16:14
@mayutj17 if that doesn't work report a bug in node ui and let me know here so I can take a look, closing for now

**Closed by Guillembonet** 2022-03-15 16:14 UTC
Labels: bug
