### ISSUE TITLE
Desktop does not connect to nodes

### ISSUE THREAD

**Issue by mjankauskas** [mysteriumnetwork/node#957] opened 2019-04-29 13:56 UTC
How to replicate:

- Start a node on desktop computer (wifi1) - Nat: sucess
- Try connecting from anouther computer (wifi2) - connecting and fails after some time
- App consumer app can successfully connect

Scenario 2:

- After testing on one computer, stop the node and start it on another computer (wifi1) - NAT success
- Connecting from another desktop (wifi2) fails
- Connecting from mobile succeeds

after some time (~5min) connection from desktop also succeeds

**Comment by vkuznecovas** [comment] 2019-05-08 11:32
Investigated this and it seems that the consumer is unable to reach the provider.

I've tested this scenario under a different router and I'm unable to reproduce it. This is most likely related to a fancy router and an artificial testing scenario.

The issue is as follows:

The provider starts a service. Makes a UPNP request to the router. The router says "ok bob, got your message loud and clear, your ports will be forwarded". But the router only queues the job to add the port forwarding without actually adding it on the fly. This means that if we rush too soon, the consumer is unable to connect as the ports are not yet forwarded properly. 

This issue has little to no real impact in a normal use scenario of node due to the following:

1) The percentage of routers that behave this way will be very limited due to the additional complexity it introduces.
2) Under normal use, you won't see the proposal of the node for a short while after startup. This allows for time to pass and the port forwarding rules to take place.

There are possible solutions to alleviate this issue. For instance, we could delay the registration of proposals for after the service start, not during the startup itself. But there is limited benefit for a solution like this.

We had a chat with @zolia about this and therefore decided to close it without further action.

**Closed by vkuznecovas** 2019-05-08 11:32 UTC
Labels: bug, component:desktop, epic:desktop-patchworks
