### ISSUE TITLE
Pre-builded images does not provide correct version information. 

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/node#441] opened 2018-10-12 04:30 UTC
```
Mysterium Node
  Version: source.dev-build
  Build info: Branch: <unknown>. Build id: dev-build. Commit:
```

**Comment by Waldz** [comment] 2018-10-14 09:14
Missing expected result

**Comment by Waldz** [comment] 2018-10-14 09:14
Marking as duplicate of #434

**Closed** 2018-10-22 12:17 UTC
Labels: bug
