### ISSUE TITLE
Error installing in Raspberry Pi 3B +

### ISSUE THREAD

**Issue by Askeshine** [mysteriumnetwork/node#4684] opened 2022-01-30 06:21 UTC
Hello , i have this error:

![imagen](https://user-images.githubusercontent.com/37356127/151689094-e14f2d6f-2004-4302-bbfc-801ab03e1096.png)

**Comment by veldspar** [comment] 2022-01-31 00:36
Install gnupg with `apt install gnupg`
Then add the repository key for Myst repo:
`apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ECCB6A56B22C536D`
Then do `apt update` and `apt install myst`
After that you'll likely need to restore DNS.
I outlined the problem and a step by step in this bug report:
https://github.com/mysteriumnetwork/node/issues/4677

Because it annoys me.

I hope this helps

**Comment by etherunit** [comment] 2022-01-31 06:51
duplicate of #4677. 
Askeshine, please follow the previously mentioned issue.

**Closed by etherunit** 2022-01-31 06:51 UTC
Labels: bug
