### ISSUE TITLE
Can't connect on localized Windows - Wireguard socket permissions problems

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#2443] opened 2020-07-07 10:46 UTC

**Comment by tadaskay** [comment] 2020-07-07 10:53
```
2020-07-01T18:56:39.000 ??? INFO: (myst) 2020/07/01 18:56:39 Starting wireguard-go version 0.0.20200320
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: event worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: handshake worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: encryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: decryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: handshake worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: encryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: decryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: encryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: encryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: decryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: handshake worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: handshake worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: decryption worker - started
2020-07-01T18:56:39.000 ??? DEBUG: (myst) 2020/07/01 18:56:39 Routine: TUN reader - started
2020-07-01T18:56:39.000 INF Setting interface configuration
2020-07-01T18:56:39.000 ERR wg-up failed error="could not listen for user API wg configuration: open \\\\.\\pipe\\ProtectedPrefix\\Administrators\\WireGuard\\myst: Access is denied."
2020-07-01T19:00:40.000 ??? ERROR: (myst) 2020/07/01 19:00:40 Failed to read packet from TUN device: file already closed
2020-07-01T19:00:40.000 ??? INFO: (myst) 2020/07/01 19:00:40 Device closing
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: handshake worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: event worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: decryption worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: handshake worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: handshake worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: decryption worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: encryption worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: encryption worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: decryption worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: encryption worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: handshake worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: decryption worker - stopped
2020-07-01T19:00:40.000 ??? DEBUG: (myst) 2020/07/01 19:00:40 Routine: encryption worker - stopped
```

**Comment by tadaskay** [comment] 2020-07-07 12:23
Reproduced this on Win 10 Familie (French)

**Comment by tadaskay** [comment] 2020-07-09 10:58
Related: #2450

The root cause is that gateway detection fails due to https://github.com/jackpal/gateway/issues/19 (fixed in the latest version)
And cleanup is not performed (#2450).
As a result, the wireguard socket is busy and any further tries result in an access denied error.

**Closed** 2020-07-10 10:04 UTC
Labels: bug, component:desktop, system:windows
