### ISSUE TITLE
Use relevant multiplier to show data transferred in NodeUI 

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/node#5585] opened 2022-11-03 12:44 UTC
Use relevant multiplier to show data transferred in NodeUI (1000 vs 1024 multipliers
bytes(SI) vs bytes(IEC)). 
Currently, CLI shows value as GiB but UI as GB. User start calculating earnings based on `GB value x initial price `and gets more than displayed in UI.
Based on: https://github.com/mysteriumnetwork/node/issues/5583

**Comment by n10ty** [comment] 2022-11-03 12:47
Example of the issue is [here](https://github.com/mysteriumnetwork/node/issues/5583)

83.57(Gb) * 1000 * 1000 * 1000 = 83 570 000 000 bytes
83 570 000 000 / 1024 / 1024 / 1024 = 77.83 (Gib)
77.83 * 0.072 = 5.589MYST

Correct to show not a 83.57 but 77.83

**Comment by Ayse-AK** [comment] 2022-11-16 20:03
@n10ty Is it fixed now?

**Closed by Ayse-AK** 2022-11-16 20:03 UTC
Labels: bug, component:node-ui
