### ISSUE TITLE
node fails to change DNS servers

### ISSUE THREAD

**Issue by Guillembonet** [mysteriumnetwork/node#4320] opened 2021-11-22 11:38 UTC
**Describe the bug**
Node fails to change DNS servers.

**To Reproduce**
1. Connect to any provider
2. Try to load any page
4. Doesn't load

**Expected behavior**
Pages load

**Environment (please complete the following information):**
 - OS: pop os (Ubuntu 21.04)
 - Desktop app version (if applicable): 10.0.0

**Additional context**
It seems that the app fails to replace DNS servers.

resolvectl returns the following when connected to a provider:
```
Link 3 (wlo1)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 212.166.132.96
       DNS Servers: 212.166.211.1 212.166.132.96
        DNS Domain: home

Link 4 (docker0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (br-a0fa6e28ac41)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 17 (myst0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/7580655/mysterium-node.log)

**Comment by Snawoot** [comment] 2021-11-22 22:51
Duplicate of https://github.com/mysteriumnetwork/node/issues/4269

**Comment by Guillembonet** [comment] 2021-11-26 10:35
This issue is still ongoing for me on Linux, Windows is working fine!

**Comment by soffokl** [comment] 2021-11-30 05:14
Desktop app package should be updated to resolve it. I have created issue for it https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/225

Closing this. 

If you want to resolve the problem not waiting the app update you need to install `resolvconf` in the system.

**Closed by soffokl** 2021-11-30 05:14 UTC
Labels: bug
