### ISSUE TITLE
[Windows] Browser traffic blocked when connected

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/node#3463] opened 2021-06-09 15:40 UTC
**Describe the bug**
Customer reported, that browser traffic is blocked when connected.
Other apps work fine, yet browser can't load webpages.
Tried everything, reinstalling, restarting etc.

Logs
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6625050/mysterium-node.log)
[mysterium-node 2.log](https://github.com/mysteriumnetwork/node/files/6625052/mysterium-node.2.log)

Android works fine for him.

**Environment (please complete the following information):**
 - Node version: 0.46.1
 - OS: Windows 10

**Comment by cvl** [comment] 2021-06-15 06:47
Update: with 0.47.1 traffic is blocked for residential IPs only. Data center IPs work ok.

Logs:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6653431/mysterium-node.log)

**Comment by Jaska8** [comment] 2021-06-17 11:21
Most of residential nodes do not work and do not route any kind of traffic for me. Tried to connect several R nodes and tried my own too, managed to connect but none of the traffic went through.
Using android phone.

**Comment by cvl** [comment] 2021-06-23 06:53
0.47.1 and 0.47.2 have the same problem.
Logs attached:
[mysterium-node.log](https://github.com/mysteriumnetwork/node/files/6699632/mysterium-node.log)

CC:
@vkuznecovas

**Comment by cvl** [comment] 2021-06-25 15:49
Any ideas on this? Quite an issue as folks can't use VPN.
CC: @chompomonim

**Comment by chompomonim** [comment] 2021-06-30 22:05
Could you please attach full logs to the issue as described in https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logging
For windows that would be (3 locations - app, node and supervisor logs respectively):

%USERPROFILE%\AppData\Roaming\MysteriumVPN\logs*.log
%USERPROFILE%.mysterium\logs\mysterium-node.log
%PROGRAMDATA%\MystSupervisor\myst_supervisor.log

**Comment by cvl** [comment] 2021-07-01 06:23
No, because node doesn't send those logs. If you need more logs than node sends, it would be a good idea to implement this.
I can't ask user to mingle with log files, this is a straight path to losing a customer.

This is unrelated to app behavior, nor supervisor.

This is a node problem. It blocks traffic only on residential IPs, and only browser traffic (therefore I assume port 80).

**Comment by cvl** [comment] 2021-07-06 07:50
Any updates on this?

**Comment by chompomonim** [comment] 2021-07-13 21:36
We tried looking on this, but we're not able to reproduce. Later this week another developer will try to look at it, maybe with his setup it will be possible to reproduce the issue.

**Comment by Snawoot** [comment] 2021-07-27 11:00
@cvl Can we have a screenshot of customer's browser when it fails to work with enabled VPN? I'd like to collect information about exact network error browser is hitting. Also some info about browser and installed extensions might be useful.

I suspect one of following scenarios:

* There is a global proxy setting in system which points to proxy in intranet (but not in the same subnet with user). When VPN enabled this proxy becomes unreachable and browser can't work. Other apps working fine because such setting is recognized mostly by browsers.
* Browser has some sort of VPN extension installed which under the hood sets browser to use some proxy server with certain credentials for it. Some services have these credentials bound to original IP address.
* User's network environment pushes Proxy Auto Configuration which is picked up by system. Sometimes it's used in corporate environment in order to filter users' traffic. Proxy auto-configuration can be disabled in system's proxy settings as well.

So, here is steps to take to diagnose and potentially fix issue:

* Collect more information
  - [ ] Error screenshot
  - [ ] Browser name
  - [ ] Installed browser extensions
  - [ ] Ask if there is any software which may filter network connections: firewalls, antiviruses, system-wide adblockers.
* Check systems proxy settings and disable proxy if there is any. Also disable proxy auto-configuration and reconnect to network or even try another internet connection (e. g. mobile data).
* Try disabling all browser extensions.
* Try to install Firefox, set it explicitly to not use proxy in it's network settings.

**Comment by cvl** [comment] 2021-07-27 11:12
Hi @Snawoot welcome aboard.

As this is a 2 months old issue, I cannot collect any more information, as the customer has long time gone (canceled and refunded).

**Comment by Snawoot** [comment] 2021-07-27 11:21
@cvl Thanks!

That's unfortunate. However, I expect same problem may manifest itself in future. In this case consider my previous comment as a run-book for such situations. Closing issue for now since no other progress on it should be expected.

**Closed by Snawoot** 2021-07-27 11:21 UTC
Labels: bug

**Comment by cvl** [comment] 2021-07-27 11:27
In general most of such information is not possible, as users are not technical, and won't spend their time collecting so much information for such a basic service as VPN :) It's easier for them just to move on to a next VPN which just works.

So the information will always be only partial.
