### ISSUE TITLE
More efficient bounty payouts

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/node#3406] opened 2021-05-18 10:33 UTC
Our bounty payouts are now very inefficient. We're doing a lot of transaction, they take a lot of time and costs a lot of money. Doing payouts in bulk would solve most of those problems.

As part of affiliate program we have build rewarder smart contracts and we could start using that system to make bounty payouts more efficient.

MMN is exposing api with information about bounty getters, we need transactor (or any other tool) to fetch that data and create needed merke root which once in a month will be sent to blockchain.

In first stage we be sending merkle root once in a month and call airdrop function to airdrop bounties
Later we may sent merkle roots once in a week, to make bounties more often and add "claim" button into WebUI/MMN to claim bounties manually at any time person wants.

Related tasks are visible in this milestone: https://github.com/mysteriumnetwork/node/milestone/56

**Comment by soffokl** [comment] 2021-05-26 04:52
is it a duplicate of the https://github.com/mysteriumnetwork/my.mysterium.network/issues/62 ?

**Closed** 2021-08-12 22:30 UTC
Labels: epic, payments
