### ISSUE TITLE
Active connections show more connections - Tequilapi (/service-sessions)

### ISSUE THREAD

**Issue by mjankauskas** [mysteriumnetwork/node#834] opened 2019-04-01 07:25 UTC
- After Service start app shows 0 connections
- When one user connects it shows 4 connections
- When one user disconnects it shows 3 connections

Expected

- After Service start app shows 0 connections
- When one user connects it shows 1 connections
- When one user disconnects it shows 0 connections

Seems like something failed after the session create and the failed sessions weren't cleared.
Same identity, 2 sessions:
<img width="325" alt="Screenshot 2019-04-01 at 11 37 56" src="https://user-images.githubusercontent.com/402965/55314500-eff00400-5472-11e9-88fc-d211bc424777.png">

After user disconnected, it's session persisted:
<img width="321" alt="Screenshot 2019-04-01 at 11 38 09" src="https://user-images.githubusercontent.com/402965/55314497-eff00400-5472-11e9-9728-10565af45ee1.png">

**Comment by Waldz** [comment] 2019-04-01 08:35
Not possible to reproduce

**Comment by ignasbernotas** [comment] 2019-04-01 10:44
@Waldz reproduced on @Germuxas mac.

**Comment by Waldz** [comment] 2019-04-03 07:04
Ticket related to #829

**Comment by vkuznecovas** [comment] 2019-04-03 07:12
The issue is irreproducible on the current version of service provider(current master). 

The scenario you encountered might have gone like this:

Consumer tries to connect to provider. Initial handshake succeeds - the session is created and persisted on the provider side. The connection establishing fails, and the network change forces the consumers session-destroy request to fail. This leaves the session hanging. Do this a few times, you'll have a few sessions hanging. 

However, these issues are now resolved. The session will eventually time out(around 2 hours) and be gone from the list. This situation is now less likely to occur in the first place as #822 is now merged in.

**Closed by vkuznecovas** 2019-04-03 07:12 UTC
Labels: bug
