### ISSUE TITLE
Send crash reports from dashboard with a click of a button

### ISSUE THREAD

**Issue by RenatBuga** [mysteriumnetwork/node#1228] opened 2019-07-24 08:36 UTC
Add in menu the item "Report Crash". After clicking, the logs are being sent and the confirmation message pops-up in an overlay box: 

Thank you! Your logs were received.

**Comment by tadaskay** [comment] 2019-08-14 12:19
Duplicate of #1251

**Closed by tadaskay** 2019-08-14 12:19 UTC
Labels: component:node, component:web-ui
